### ISSUE TITLE
Algorithmus ggf. Ensemble providen

### ISSUE THREAD

**Issue by florian99797** [hannahweber244/CryptoSentiment#13]
tf-idf : 80% Accuracy

Ausprobieren von CNN für Sentiment, ELMO Enbeddings

**Comment by florian99797** [comment]
CNNs etwa 50% Accuracy

**Comment by florian99797** [comment]
2 Bugs bei der sind eigene Issues. Status hier zu sehen:

https://github.com/hannahweber244/CryptoSentiment/issues/2
https://github.com/hannahweber244/CryptoSentiment/issues/4

**Comment by hannahweber244** [comment]
CNNs auf den in #16 beschriebenen Datensatzkombinationen erreicht eine Accuracy von 97%.
Bereitgestellt werden für den Vectorizer die mapping Dictionaries index_to_token und token_to_index, zusätzlich wird die aus dem Training bekannte Embeddingmatrix bereitgestellt und die .pt Datei des trainierten Modells. Die Wordembeddings sind während des Trainings über 30 Epochen mit optimiert worden. Aus dem Training bedingt können nur Sequenzen bis zu einer Sequenzlänge von 30 nach der Vorverarbeitung (also ohne stopwords) bearbeitet werden, dies ist für die gegebene Aufgabenstellung jedoch absolut ausreichend. Die Dateien werden über einen Google Drive Link bereitgestellt und beim Start der Applikation automatisiert heruntergeladen, da die Dateigrößen der Embeddingmatrix und des Modells zu groß für Github sind
