### ISSUE TITLE
Modell auf Basis von zwei Datensätzen

### ISSUE THREAD

**Issue by hannahweber244** [hannahweber244/CryptoSentiment#16]
- in Produktivumgebung sehen Ergebnisse auf den realen Daten nicht so gut aus, wie aus Trainings- und Testphase bekannt
- Kombinieren von zwei Datensätzen um Ergebnisse zu sehen

**Comment by Julian-Greil** [comment]
- Ergebnisse wenn Modell auf Twitter/Reddit Daten getestet auf Financial News Daten. Ergebnisse nicht zufriedenstellend. Daher andere Trainigsdaten suchen.
- Ergebnisse Visualisiert: 
![image](https://user-images.githubusercontent.com/58034641/124780640-0edb7b80-df43-11eb-8386-745651b69da8.png)

**Comment by hannahweber244** [comment]
Neue, finanzenspezifische Datensätze:
- https://www.kaggle.com/vivekrathi055/sentiment-analysis-on-financial-tweets?select=tweet_sentiment.csv
- https://www.kaggle.com/ankurzing/sentiment-analysis-for-financial-news

Sentimentdaten, drei Klassen, finanzbezogen, Newsheadlines + Twitterdaten

**Comment by hannahweber244** [comment]
Kombination von zwei Datensätzen wird als Trainingsgrundlage genutzt, da diese thematisch eine gute Datengrundlage hergeben und ein erfolgreiches Training begünstigen
