### ISSUE TITLE
Direkter Vergleich Modellergebnisse

### ISSUE THREAD

**Issue by hannahweber244** [hannahweber244/CryptoSentiment#20]
In diesem Issue wird eine Übersicht über die in diesem Projekt implementierten und getesteten Modelle gegeben. Dazu gehören

- CNN + FC NN auf den in #16 beschriebenen Datensätzen, verwendet GloVE-Embeddings
- LSTM + FC NN auf den in #16  beschriebenen Datensätzen, verwendet GloVE-Embeddings
- TF-IDF + FC NN auf den in #16 beschriebenen Datensätzen, verwendet GloVE-Embeddings

**Comment by Julian-Greil** [comment]
Modellergebnisse visualisiert und vorgestellt
